version: 2.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $REGISTRY_ID -p $REGISTRY_PASSWORD
      - run: docker pull aquasec/scanner-cli:3.2
      - run: docker logout
      - run: docker build -t myimage:mytag .
      - run: |
          docker run -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/scanner-cli:3.2 scan \
          -H http://aqua-server1.aquaseclabs.com:8080 \
          -U svc-scanner \
          -P vpn12345 \
          --local myimage:mytag
